#!/usr/bin/env bash
set -euo pipefail

print_step() {
    echo
    echo "########################################################################"
    echo "STEP $1: $2"
    echo "########################################################################"
}

# This script is the estimated-depth pickupbowl_1 SAM2 -> SAM3 -> mesh postprocess pipeline.
#
# You should edit the configuration section below for your own machine.
# In particular, replace repo paths, dataset paths, and prompt arguments as needed.
#
# For Tyler's current setup:
#   SAM2 repo: /home/tylerlum/github_repos/segment-anything-2-real-time/
#   SAM3 repo: /home/tylerlum/github_repos/sam-3d-objects/


################################################################################
# User configuration: update these for your own machine
################################################################################

# Path to this SAM2 repo.
SAM2_REPO="/home/tylerlum/github_repos/segment-anything-2-real-time"

# Path to the SAM3 repo that contains run_inference.py.
SAM3_REPO="/home/tylerlum/github_repos/sam-3d-objects"

# Input demo directory. Expected to contain rgb/, depth/, and cam_K.txt.
DEMO_DIR="${DEMO_DIR:-/juno/u/yufeid/project_storage/shared_folder/input_data/megasam_depth_0323/pickupbowl_1}"

# Output directory for SAM3 mesh results and downstream processed assets.
OUTPUT_DIR="${OUTPUT_DIR:-${SAM3_REPO}/outputs/pickupbowl_1_estimated_depth}"

# Existing object masks for the original RGB video.
# For pickupbowl_1 these were already generated by GroundingDINO/SAM and are
# named mask_00000.png, mask_00001.png, ...
OBJECT_MASK_DIR="${OBJECT_MASK_DIR:-${DEMO_DIR}/IDEA-Research_grounding-dino-base_masks_bowl}"

# SAM3 expects one input directory containing rgb/, depth/, masks/, and cam_K.txt.
# Estimated-depth frames are lower-resolution than the original RGB/masks, so this
# staging folder keeps the source dataset untouched while resizing RGB/masks to
# the depth resolution used by cam_K.txt.
SAM3_INPUT_DIR="${SAM3_INPUT_DIR:-${OUTPUT_DIR}/sam3_input}"

# Set this to 1 only if you want to regenerate object masks with SAM2 below.
# Leaving it at 0 uses OBJECT_MASK_DIR as-is.
RUN_OBJECT_MASK_SAM2="${RUN_OBJECT_MASK_SAM2:-0}"

# Prompt arguments for the initial object segmentation.
# Default args use interactive two-positive-click mode.
#
# Examples:
#   OBJECT_PROMPT_ARGS=(--prompt_x 664 --prompt_y 335)
#   OBJECT_PROMPT_ARGS=(--use_second_prompt)         # interactive two-positive-click mode
#   OBJECT_PROMPT_ARGS=(--use_negative_prompt)       # interactive positive+negative-click mode
OBJECT_PROMPT_ARGS=(--use_second_prompt)

# Prompt arguments for the handle and head masks on the rendered SAM3 RGB frames.
# These are usually separate interactive runs. The default asks for a positive
# click and then a negative click.
HANDLE_PROMPT_ARGS=(--use_negative_prompt)
HEAD_PROMPT_ARGS=(--use_negative_prompt)


################################################################################
# Environment helpers: replace these if your setup differs
################################################################################

sam2() {
    # Activate the SAM2 environment and run commands from the SAM2 repo.
    #
    # Edit this function for your machine if:
    # - your SAM2 repo lives elsewhere
    # - your environment activation differs
    # - you use conda instead of uv
    #
    # Current Tyler setup:
    # - repo: /home/tylerlum/github_repos/segment-anything-2-real-time
    # - env:  source .venv/bin/activate
    cd "${SAM2_REPO}"
    # shellcheck disable=SC1091
    source .venv/bin/activate
    export PYTHONPATH="${SAM2_REPO}:${PYTHONPATH:-}"
    "$@"
}

sam3() {
    # Activate the SAM3 environment and run commands from the SAM3 repo.
    #
    # Edit this function for your machine if:
    # - your SAM3 repo lives elsewhere
    # - your SAM3 environment activation differs
    #
    # Current Tyler setup uses the SAM3 local .venv311.
    # If your SAM3 setup is conda-based, replace the source line with your own activation.
    #
    # Note: run_inference.py imports `viser` at top level, so `viser` must be installed
    # in the SAM3 environment, not the SAM2 environment.
    cd "${SAM3_REPO}"
    # shellcheck disable=SC1091
    source .venv311/bin/activate
    export PYTHONPATH="${SAM3_REPO}:${PYTHONPATH:-}"
    "$@"
}

require_sam2_imports() {
    sam2 python - <<'PY'
import cv2
import torch
print("SAM2 env OK")
PY
}

require_sam3_imports() {
    sam3 python - <<'PY'
import trimesh
import tyro
import viser
print("SAM3 env OK")
PY
}

stage_sam3_inputs() {
    print_step "0.5" "Staging SAM3 inputs at estimated-depth resolution"

    mkdir -p "${OUTPUT_DIR}"
    mkdir -p "${SAM3_INPUT_DIR}"
    rm -rf "${SAM3_INPUT_DIR}/rgb" "${SAM3_INPUT_DIR}/masks"
    mkdir -p "${SAM3_INPUT_DIR}/rgb" "${SAM3_INPUT_DIR}/masks"
    ln -sfn "${DEMO_DIR}/depth" "${SAM3_INPUT_DIR}/depth"
    ln -sfn "${DEMO_DIR}/cam_K.txt" "${SAM3_INPUT_DIR}/cam_K.txt"

    export DEMO_DIR OBJECT_MASK_DIR SAM3_INPUT_DIR
    sam2 python - <<'PY'
import os
from pathlib import Path

import cv2

demo_dir = Path(os.environ["DEMO_DIR"])
mask_dir = Path(os.environ["OBJECT_MASK_DIR"])
stage_dir = Path(os.environ["SAM3_INPUT_DIR"])

rgb_files = sorted((demo_dir / "rgb").glob("*.png"))
depth_files = sorted((demo_dir / "depth").glob("*.png"))
mask_files = sorted(mask_dir.glob("*.png"))

if not rgb_files:
    raise SystemExit(f"No RGB frames found in {demo_dir / 'rgb'}")
if not depth_files:
    raise SystemExit(f"No depth frames found in {demo_dir / 'depth'}")
if not mask_files:
    raise SystemExit(f"No masks found in {mask_dir}")

for i, rgb_path in enumerate(rgb_files):
    depth_path = depth_files[min(i, len(depth_files) - 1)]
    depth = cv2.imread(str(depth_path), cv2.IMREAD_UNCHANGED)
    rgb = cv2.imread(str(rgb_path), cv2.IMREAD_COLOR)
    if depth is None:
        raise SystemExit(f"Could not read depth frame: {depth_path}")
    if rgb is None:
        raise SystemExit(f"Could not read RGB frame: {rgb_path}")
    h, w = depth.shape[:2]
    if rgb.shape[:2] != (h, w):
        print(f"Warning: resizing RGB {rgb_path.name} from {rgb.shape[:2]} to depth size {(h, w)}")
        rgb = cv2.resize(rgb, (w, h), interpolation=cv2.INTER_AREA)
    cv2.imwrite(str(stage_dir / "rgb" / rgb_path.name), rgb)

for i, mask_path in enumerate(mask_files):
    depth_path = depth_files[min(i, len(depth_files) - 1)]
    depth = cv2.imread(str(depth_path), cv2.IMREAD_UNCHANGED)
    mask = cv2.imread(str(mask_path), cv2.IMREAD_UNCHANGED)
    if depth is None:
        raise SystemExit(f"Could not read depth frame: {depth_path}")
    if mask is None:
        raise SystemExit(f"Could not read mask: {mask_path}")
    h, w = depth.shape[:2]
    if mask.shape[:2] != (h, w):
        print(f"Warning: resizing mask {mask_path.name} from {mask.shape[:2]} to depth size {(h, w)}")
        mask = cv2.resize(mask, (w, h), interpolation=cv2.INTER_NEAREST)
    cv2.imwrite(str(stage_dir / "masks" / mask_path.name), mask)

print(f"Staged {len(rgb_files)} RGB frames and {len(mask_files)} masks in {stage_dir}")
PY
}


################################################################################
# Sanity checks
################################################################################

if [[ ! -d "${DEMO_DIR}/rgb" ]]; then
    echo "Missing RGB directory: ${DEMO_DIR}/rgb" >&2
    exit 1
fi

if [[ ! -d "${DEMO_DIR}/depth" ]]; then
    echo "Missing depth directory: ${DEMO_DIR}/depth" >&2
    exit 1
fi

if [[ ! -d "${OBJECT_MASK_DIR}" ]]; then
    echo "Missing object mask directory: ${OBJECT_MASK_DIR}" >&2
    exit 1
fi

# Fail early with a clear message if either environment is missing required deps.
print_step "0" "Checking SAM2 and SAM3 environments"
require_sam2_imports
require_sam3_imports
stage_sam3_inputs


################################################################################
# Step 1: Optionally run SAM2 on the original RGB frames to create object masks
################################################################################

# The default pickupbowl_1 path already has good masks in OBJECT_MASK_DIR, so
# this step is skipped unless RUN_OBJECT_MASK_SAM2=1.
if [[ "${RUN_OBJECT_MASK_SAM2}" == "1" ]]; then
    # Replace OBJECT_PROMPT_ARGS above with your own prompt mode.
    # If you use an interactive mode like --use_second_prompt, the script will open
    # the first frame and wait for your clicks.
    print_step "1" "Running SAM2 on the original RGB frames to create object masks"
    sam2 python video_sam2.py \
        --input_dir "${DEMO_DIR}/rgb" \
        --output_dir "${OBJECT_MASK_DIR}" \
        "${OBJECT_PROMPT_ARGS[@]}"
else
    print_step "1" "Using existing object masks"
    echo "OBJECT_MASK_DIR=${OBJECT_MASK_DIR}"
fi


################################################################################
# Step 2: Run SAM3 to reconstruct the object mesh from rgb/depth/object masks
################################################################################

# This assumes SAM3's run_inference.py expects:
# - input_dir containing rgb/, depth/, and masks/
# - output_dir where mesh/, rgb/, depth/, cam_poses.npy, etc. will be written
print_step "2" "Running SAM3 to reconstruct the object mesh"
sam3 python run_inference.py \
    --input_dir "${SAM3_INPUT_DIR}" \
    --output_dir "${OUTPUT_DIR}"


################################################################################
# Step 3: Render the mesh into an orbit video and save RGB/depth/camera data
################################################################################

# This writes rendered RGB/depth frames into OUTPUT_DIR for downstream part masking.
print_step "3" "Rendering the reconstructed mesh into RGB/depth views"
sam2 python create_mesh_video.py \
    --mesh-filepath "${OUTPUT_DIR}/mesh/mesh.obj" \
    --output_dir "${OUTPUT_DIR}"


################################################################################
# Step 4: Run SAM2 on rendered frames to get handle masks
################################################################################

# Replace HANDLE_PROMPT_ARGS above with your own prompt mode if needed.
print_step "4" "Running SAM2 on rendered frames to create handle masks"
sam2 python video_sam2.py \
    --input_dir "${OUTPUT_DIR}/rgb" \
    --output_dir "${OUTPUT_DIR}/handle_masks" \
    "${HANDLE_PROMPT_ARGS[@]}"


################################################################################
# Step 5: Run SAM2 on rendered frames to get head masks
################################################################################

# Replace HEAD_PROMPT_ARGS above with your own prompt mode if needed.
print_step "5" "Running SAM2 on rendered frames to create head masks"
sam2 python video_sam2.py \
    --input_dir "${OUTPUT_DIR}/rgb" \
    --output_dir "${OUTPUT_DIR}/head_masks" \
    "${HEAD_PROMPT_ARGS[@]}"


################################################################################
# Step 6: Merge masks across views, compute handle frame, crop handle mesh
################################################################################

print_step "6" "Merging masks in 3D and exporting handle-frame meshes"
sam2 python process_mesh.py \
    --output_dir "${OUTPUT_DIR}"


################################################################################
# Final artifact
################################################################################

print_step "7" "Final artifact"
echo "Expected transformed mesh:"
echo "  ${OUTPUT_DIR}/mesh_handle_frame/mesh_handle_frame.obj"
ls "${OUTPUT_DIR}/mesh_handle_frame/mesh_handle_frame.obj"
